config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :restaurant
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :list_user
  has_many :list_items
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :restaurant
  belongs_to :list
end

app/models/list_user.rb
class ListUser < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  
	has_many :labels
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
    @restaurants = Restaurant.where.not(latitude: nil, longitude: nil)

    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: { content: render_to_string(partial: "/restaurants/map_box", locals: { restaurant: restaurant }) }
        # Uncomment the above line if you want each of your markers to display a info window when clicked
        # (you will also need to create the partial "/restaurants/map_box")
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%#= javascript_include_tag "application" %>
    <%#= javascript_pack_tag 'application' %>
    
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    
    <%= yield %>

    <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
    <%#= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			
			<h1>Pages#home</h1>
			<p>Find me in app/views/pages/home.html.erb</p>
						
		</div>
	</div>
</div>

app/views/restaurants/_map_box.erb
<div class="info-window">
  <%= restaurant.name %>
</div>

app/views/restaurants/index.html.erb
<!-- container -->
<div class="container">
 
  <!-- list-items -->
  <div class="list-items mt-3">

  	<%= @restaurants.each do |restaurant| %>
  		<!-- list-item -->
			<div class="list-item">
				<img src="images/res_1.png" alt="" class="">
				<div class="list-item-hashtag col-sm-3">
					<h5><%= restaurant.name %></h5>
					<p><%= restaurant.address %></p>
					<a href="#">#Lebanese &nbsp;</a>
	        <a href="#">#Bistro &nbsp;</a>
	        <a href="#">#Restaurant &nbsp;</a>
	        <a href="#">#Berlin &nbsp;</a>
	        <a href="#">#Neukölln &nbsp;</a>
				</div>
				<div class="list-item-note">
        <ul>
          <li>Note: A bit smelly due to the open grill</li>
          <li>Favourite: Excellent vegi plate</li>
          <li>Source: Google Maps</li>
          <li>Visited: &nbsp; 
            <i class="fas fa-check"></i>
          </li>
        </ul>
      </div>
      <div class="list-item-action">
        <a href="#">
          <i class="fas fa-share" style="font-size:25px;"></i>
        </a>
      </div>
		</div>
  	<% end %>
  	<!-- /list-item -->
   
	</div>
	<!-- /list-items -->

</div>
<!-- /container -->

<!-- map -->
<div
  id="map"
  class="map-style"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
></div>                                                   
<!-- /map -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>